package com.example.lavaturopa.enums;

public enum TipoPrenda {
    CAMISA,  PANTALON, FALDA, VESTIDO, CHAQUETA, ABRIGO, SUETER, CAMISETA, JEANS, SHORTS, TRAJE, CORBATA, ROPAINTERIOR, CALCETINES, TOALLA, SABANA, MANTA, ALMOHADA, CORTINA
}
